[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/impact-logic/submit"
  to = "/.netlify/functions/submit"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
